version: "3.8"
services: 
  vrising:
    container_name: vrising-server
    image: ghcr.io/zackhorvath/vrising-docker:latest
    volumes: 
      - /vrising/saves:/root/.wine/drive_c/users/root/AppData/LocalLow/Stunlock Studios/VRisingServer/Saves
      - /vrising/settings:/root/.wine/drive_c/users/root/AppData/LocalLow/Stunlock Studios/VRisingServer/Settings/
    ports: 
      - "27015:27015/udp"
      - "27016:27016/udp"
    restart: unless-stopped
    tty: true